# Generated by Django 5.1.5 on 2025-02-01 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Anubis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="markdowncontent",
            old_name="title",
            new_name="file_name",
        ),
    ]
